### ISSUE TITLE
Build issue missing Library

### ISSUE THREAD

**Issue by Dontmindmes** [Kirides/screen-share#1]
![image](https://user-images.githubusercontent.com/32211128/126714345-0cf6b307-d1f5-485f-bf19-d793e09a28e4.png)

**Comment by kirides** [comment]
How did you try to build it?
What go version were you using?
What OS are you trying to build this on?

**Comment by Dontmindmes** [comment]
i used "go build"

using go version go1.16.6 windows/amd64
Windows 10

**Comment by kirides** [comment]
Do you perhaps have go modules disabled?
