### ISSUE TITLE
Modularity/Public packages

### ISSUE THREAD

**Issue by rdnt** [Kirides/screen-share#3]
Hi! I have used your code to facilitate screen capturing for an app I am making, but I had to copy the repo locally and replace some imports. Would you be interested in making the code more friendly for other users that want to import parts of it (e.g. d3d, swizzle)? I can also create a PR that adds that if you don't want to invest the time to do it.

Thanks in advance!

**Comment by kirides** [comment]
> more friendly for other users that want to import parts of it (e.g. d3d, swizzle)?

what do you mean by that? Which parts do you want to reuse?
everything at the "root" is more or less "application specific" code.

Which parts did you need and / or want to be refactored?

Edit: i just published a more cleaned up version of the source code and renamed the repo appropriately.

**Comment by rdnt** [comment]
@kirides Looks good! Thank you.
