### ISSUE TITLE
Consider splitting up into multiple modules

### ISSUE THREAD

**Issue by merlinaudio** [Kirides/screen-share#4]
First off, thank you so much for building screencapture!!

Would you consider splitting it up into multiple modules? As it stands, I think this is *the only* Golang module that implements IDXGI.

Other Windows API wrappers don't even support it, but it's clearly needed: https://github.com/lxn/win/issues/122

You could also consider setting up GitHub Sponsors :)

Many thanks from Stuttgart

**Comment by kirides** [comment]
I just migrated this repository to https://github.com/kirides/go-d3d where i restructured the code in a way, that others can reuse parts of the DXGI/D3D11 implementations for their own needs.

This repository will be archived.
