### ISSUE TITLE
screencapture example passes wrong display index

### ISSUE THREAD

**Issue by merlinaudio** [Kirides/screen-share#5]
The screencapture example once uses a param called `n` for getting the screen bounds `screenshot.GetScreenBounds`, which takes the displays index `displayIndex`, and then uses the same parameter for `d3d.NewIDXGIOutputDuplication`, which takes the displays **number** `output`.

I believe this is an off-by-one error because I had to do this for my records not to get messed up:

```go
bounds := screenshot.GetDisplayBounds(displayNum - 1)
//                                                 ^ if not subtracting one from the parameter passed
//                                                   into NewIDXGIOutputDupilcation, this is wrong
```

**Comment by merlinaudio** [comment]
![image](https://user-images.githubusercontent.com/85179170/209477849-0dad18e7-bc49-4621-ba32-fc58ab15951d.png)

This is what a recording ended up looking like when NOT doing this ^

**Comment by kirides** [comment]
i couldn't reproduce this behavior, would you be so kind and retry the respective example from https://github.com/kirides/go-d3d ?

This issue will be closed due to this repo being archived
